### ISSUE TITLE
Output data

### ISSUE THREAD

**Issue by biancacap** [bubingy/HeadPoseEstimate#2]
Hi, great program! I am wondering how I can get output data for roll, pitch and yaw after getting a video output. Thanks.

**Comment by bubingy** [comment]
@biancacap please see line 86 in `estimate_head_pose_video.py`:
```
euler_angle_lst, directions_lst, landmarks_lst = estimate_head_pose(
      ver_lst, True
)
```
`euler_angle_lst` is the list of Euler Angle for all faces detected in current frame.
```
[
    [roll1, yaw1, pitch1], # for face 1
    [roll2, yaw2, pitch2], # for face 2
        .
        .
]
```
