### ISSUE TITLE
3D facial landmarks

### ISSUE THREAD

**Issue by tkzky** [bubingy/HeadPoseEstimate#3]
您好，请问得到的三维人脸特征点坐标的Z轴是深度信息吗？谢谢！

**Comment by bubingy** [comment]
是的，但是如果要利用这些坐标，建议用matplotlib画出这些点，记得留意它们的方向^_^

**Comment by tkzky** [comment]
您好，这个Z坐标貌似不是人脸距离相机的深度值吧

**Comment by bubingy** [comment]
抱歉没看到这个回复。z不是人脸距离相机的深度值，这里的深度信息其实是指人脸表面各点相对于照片平面的距离。
