### ISSUE TITLE
Different results from 3ddfa_v2 model output

### ISSUE THREAD

**Issue by ry85** [bubingy/HeadPoseEstimate#4]
Hi,

Thanks for sharing the code.

Actually, I applied your code on one of the image and these are the pose values: roll: 0.6101518331015396, yaw: 2.5585565750915165, pitch: -9.556793182165018.

However, for the same image the 3ddfa_v2 model pose values are (using theirs pose.py script): roll: 2.7, yaw: -2.2, pitch: -1.2

I don't know why there is a difference between the two results. Ideally, they should have been the same. (Notice for yaw they are opposite in sign)

**Comment by bubingy** [comment]
Thanks for the feedback. 
Do you get pose value from 3DDFA_V2/utils/pose.py? I think it calculates Euler angles by solving a PnP problem(Perspective-n-Point problem). My approach is estimating orientation with PCA(see README.md for more details), then calculate rotation matrix by [Kabsch algorithm](https://en.wikipedia.org/wiki/Kabsch_algorithm). 
I'm still investigating how to convert rotation matrix to Euler angles, so I can't tell why the yaw angle are opposite in sign.
